version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - errcheck
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - performance
        - style
        - experimental
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      confidence: 0.1
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - revive
        text: 'package-comments: should have a package comment'
      - linters:
          - dupl
          - gosec
        path: _test\.go
      - linters:
          - govet
        text: 'shadow: declaration of "err" shadows'

formatters:
  enable:
    - gofmt
    - goimports
    - gci
